
#let AA = math.upright(math.bold("A"))
#let BB = math.upright(math.bold("B"))
#let CC = math.upright(math.bold("C"))
#let DD = math.upright(math.bold("D"))
#let EE = math.upright(math.bold("E"))
#let FF = math.upright(math.bold("F"))
#let GG = math.upright(math.bold("G"))
#let HH = math.upright(math.bold("H"))
#let II = math.upright(math.bold("I"))
#let JJ = math.upright(math.bold("J"))
#let KK = math.upright(math.bold("K"))
#let LL = math.upright(math.bold("L"))
#let MM = math.upright(math.bold("M"))
#let NN = math.upright(math.bold("N"))
#let OO = math.upright(math.bold("O"))
#let PP = math.upright(math.bold("P"))
#let QQ = math.upright(math.bold("Q"))
#let RR = math.upright(math.bold("R"))
#let SS = math.upright(math.bold("S"))
#let TT = math.upright(math.bold("T"))
#let UU = math.upright(math.bold("U"))
#let VV = math.upright(math.bold("V"))
#let WW = math.upright(math.bold("W"))
#let XX = math.upright(math.bold("X"))
#let YY = math.upright(math.bold("Y"))
#let ZZ = math.upright(math.bold("Z"))

